Imports

In [27]:
import numpy as np


Task 1

In [28]:
array_size = int(input("Input array size: "))

first_array = np.linspace(0, 100, num=array_size)
# I decided to round numbers to 2 decimal places
first_array = np.round(first_array, 2)
print(f"first array\t=> {repr(first_array)}")

second_array = np.linspace(0, 1, num=array_size)
second_array = np.round(second_array, 2)
print(f"second array\t=> {repr(second_array)}")

print(f"sum\t\t=> {list([first_array[i] + second_array[i] 
        for i in range(array_size)])}")
print(f"sum(np)\t\t=> {repr(first_array + second_array)}")


first array	=> array([  0.,  25.,  50.,  75., 100.])
second array	=> array([0.  , 0.25, 0.5 , 0.75, 1.  ])
sum		=> [0.0, 25.25, 50.5, 75.75, 101.0]
sum(np)		=> array([  0.  ,  25.25,  50.5 ,  75.75, 101.  ])


Task 2

In [29]:
f_matrix_rows = int(input("Input number of rows for first matrix: "))
f_matrix_cols = int(input("Input number of cols for first matrix: "))

# if the result of multiply of all elements was meant, then 
# user input might make sense
s_matrix_rows = f_matrix_cols
s_matrix_cols = int(input("Input number of cols for second matrix: "))

# * explanation: I use list comprehension to create array of arrays 
# at first, I create row with appropriate element from <first_array>
# I use (i % len(first_array)) to prevent IndexOutOfRange,
# so if <i> is greater than <first_array> size, it will use elements
# from start instead
# and at last - repeat that operation for number of rows
first_matrix = np.array(
    [
        [first_array[i % len(first_array)]] * f_matrix_cols
        for i in range(f_matrix_rows)
    ]
)
print("first matrix\t=>")
print(repr(first_matrix))

second_matrix = np.array(
    [
        [second_array[i % len(second_array)] for i in range(s_matrix_cols)]
        for _ in range(s_matrix_rows)
    ]
)

print("second matrix =>")
print(repr(second_matrix))



first matrix	=>
array([[  0.,   0.,   0.,   0.],
       [ 25.,  25.,  25.,  25.],
       [ 50.,  50.,  50.,  50.],
       [ 75.,  75.,  75.,  75.],
       [100., 100., 100., 100.],
       [  0.,   0.,   0.,   0.]])
second matrix =>
array([[0.  , 0.25, 0.5 , 0.75, 1.  , 0.  , 0.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 0.  , 0.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 0.  , 0.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 0.  , 0.25]])


In [30]:


# * fixing numpy array output
np.set_printoptions(linewidth=160)

multiplied_matrix = []
for row in first_matrix:
    temp_row = []
    for column in second_matrix.T:
        temp_row.append(sum(map(lambda x, y: x * y, row, column)))
    multiplied_matrix.append(temp_row)

multiplied_matrix = np.array(multiplied_matrix)
print("multiplied matrix =>")
print(repr(multiplied_matrix))

print("multiplied matrix (numpy) =>")
print(repr(np.matmul(first_matrix, second_matrix)))

multiplied matrix =>
array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  25.,  50.,  75., 100.,   0.,  25.],
       [  0.,  50., 100., 150., 200.,   0.,  50.],
       [  0.,  75., 150., 225., 300.,   0.,  75.],
       [  0., 100., 200., 300., 400.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.]])
multiplied matrix (numpy) =>
array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  25.,  50.,  75., 100.,   0.,  25.],
       [  0.,  50., 100., 150., 200.,   0.,  50.],
       [  0.,  75., 150., 225., 300.,   0.,  75.],
       [  0., 100., 200., 300., 400.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.]])
